(()=>{
const {CERTS,buildBank}=window.CLAUDE_CERT;
const app=document.getElementById('app');
const STORE='claude-cert-practice-v3';
const THEME='claude-cert-theme';
let tickHandle=null,toastHandle=null,openSheet=null;
const banks=Object.fromEntries(Object.keys(CERTS).map(k=>[k,buildBank(k)]));
const bankMaps=Object.fromEntries(Object.entries(banks).map(([k,b])=>[k,new Map(b.map(q=>[q.id,q]))]));
const defaultState=()=>({active:{},history:[]});
function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return defaultState()}}
let state=load();
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function rnd(n){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=rnd(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function id(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function sameSet(a=[],b=[]){if(a.length!==b.length)return false;const x=[...a].sort((m,n)=>m-n),y=[...b].sort((m,n)=>m-n);return x.every((v,i)=>v===y[i])}
function fmtTime(sec){sec=Math.max(0,sec|0);const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function dateFmt(x){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}
function quota(domains,total){const raw=domains.map(([name,w])=>({name,raw:w/100*total,n:Math.floor(w/100*total)}));let left=total-raw.reduce((a,x)=>a+x.n,0);raw.sort((a,b)=>(b.raw-b.n)-(a.raw-a.n));for(let i=0;i<left;i++)raw[i%raw.length].n++;return Object.fromEntries(raw.map(x=>[x.name,x.n]))}
function draw(cert){const cfg=CERTS[cert],qs=banks[cert],q=quota(cfg.domains,cfg.count),picked=[];for(const [domain] of cfg.domains){const pool=qs.filter(x=>x.domain===domain),groups=new Map();for(const x of pool){const key=x.concept||(x.id.startsWith('extra-')?x.id:x.id.split('-').slice(0,2).join('-'));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)}const first=shuffle([...groups.values()]).map(g=>shuffle(g)[0]),need=q[domain];picked.push(...first.slice(0,need));if(first.length<need){const used=new Set(picked.map(x=>x.id));picked.push(...shuffle(pool.filter(x=>!used.has(x.id))).slice(0,need-first.length))}}return shuffle(picked).map(x=>x.id)}
function makeAttempt(cert){const cfg=CERTS[cert];return {id:id(),cert,questionIds:draw(cert),answers:{},flags:[],current:0,remaining:cfg.minutes*60,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function activeAttempt(cert){return state.active[cert]||null}
function findAttempt(id){for(const a of Object.values(state.active))if(a&&a.id===id)return {type:'active',a};const r=state.history.find(x=>x.id===id);return r?{type:'result',a:r}:null}
function answerCount(a){return Object.values(a.answers||{}).filter(x=>x?.length).length}
function qFor(a,idx=a.current){return bankMaps[a.cert].get(a.questionIds[idx])}
function stopTick(){if(tickHandle){clearInterval(tickHandle);tickHandle=null}}
function startTick(a){stopTick();tickHandle=setInterval(()=>{const current=findAttempt(a.id);if(!current||current.type!=='active'){stopTick();return}current.a.remaining=Math.max(0,current.a.remaining-1);current.a.updatedAt=new Date().toISOString();const el=document.getElementById('timer');if(el)el.textContent=fmtTime(current.a.remaining);if(current.a.remaining%5===0)save();if(current.a.remaining<=0){save();stopTick();submitExam(current.a,true)}},1000)}
function theme(){return localStorage.getItem(THEME)||'dark'}
function applyTheme(){document.documentElement.dataset.theme=theme();document.querySelector('meta[name="theme-color"]').content=theme()==='dark'?'#111310':'#f4f2ec'}
function toggleTheme(){localStorage.setItem(THEME,theme()==='dark'?'light':'dark');applyTheme();render()}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;clearTimeout(toastHandle);toastHandle=setTimeout(()=>t.remove(),1800)}
function nav(active='exams'){return `<nav class="bottom-nav" aria-label="Primary"><button class="nav-btn ${active==='exams'?'active':''}" data-action="go" data-route="home"><span class="nav-icon">⌂</span><span>Exams</span></button><button class="nav-btn ${active==='history'?'active':''}" data-action="go" data-route="history"><span class="nav-icon">↺</span><span>History</span></button></nav>`}
function header(){return `<header class="topbar"><div class="topbar-inner"><div class="brand"><span class="mark">C</span><span>Claude Cert Practice</span></div><div class="top-actions"><button class="icon-btn" data-action="theme" aria-label="Toggle color theme" title="Toggle theme">${theme()==='dark'?'☼':'◐'}</button></div></div></header>`}
function home(){stopTick();const cards=Object.entries(CERTS).map(([k,c])=>{const a=activeAttempt(k);return `<article class="exam-card" style="--track:${c.accent}"><h2>${esc(c.short)}</h2><div class="meta">${c.code} · ${c.count} questions · ${c.minutes} minutes<br>${banks[k].length} original blueprint-aligned questions in the bank</div><div class="card-actions"><button class="btn primary" data-action="new" data-cert="${k}">${a?'Start fresh':'Start exam'}</button>${a?`<button class="btn" data-action="resume" data-cert="${k}">Resume</button>`:''}</div>${a?`<div class="resume-note">In progress · ${answerCount(a)}/${c.count} answered · ${fmtTime(a.remaining)} remaining</div>`:''}</article>`}).join('');
return `<div class="shell">${header()}${nav('exams')}<main class="main"><section class="hero"><div class="eyebrow">Exam simulator</div><h1>Practice the exam. Review what you missed. Repeat.</h1><p>Each attempt draws a fresh, blueprint-weighted set from a larger original question bank. Attempts and answers stay in this browser so you can resume or review them later.</p></section><section class="exam-grid">${cards}</section></main></div>`}
function historyPage(){stopTick();const rows=state.history.map(r=>{const c=CERTS[r.cert];return `<article class="history-item"><div><div class="history-title">${esc(c.short)}</div><div class="history-sub">${dateFmt(r.completedAt)} · ${r.correctCount}/${c.count} correct · ${r.needsReview} need review</div></div><div><div class="score">${r.percent}%</div><button class="btn ghost" data-action="review" data-id="${r.id}">Review</button></div></article>`}).join('');return `<div class="shell">${header()}${nav('history')}<main class="main"><div class="page-head"><div><div class="eyebrow">Saved locally</div><h1>Exam history</h1><p>Open any attempt to review every answer.</p></div>${state.history.length?'<button class="btn ghost danger" data-action="clear-history">Clear</button>':''}</div>${rows?`<section class="history-list">${rows}</section>`:`<div class="empty"><strong>No completed exams yet.</strong>Finish an exam and it will stay here for review.</div>`}</main></div>`}
function examPage(a){const c=CERTS[a.cert],q=qFor(a),ans=a.answers[q.id]||[],flag=a.flags.includes(q.id);startTick(a);return `<div class="exam-shell"><header class="exam-top"><div class="exam-top-inner"><div class="exam-progress">${a.current+1} / ${c.count}</div><div class="timer" id="timer">${fmtTime(a.remaining)}</div><div class="exam-tools"><button class="icon-btn flag ${flag?'active':''}" data-action="flag" title="Flag for review" aria-label="${flag?'Unflag':'Flag'} question">⚑</button><button class="icon-btn" data-action="navigator" title="Question navigator" aria-label="Open question navigator">▦</button><button class="icon-btn" data-action="exit" title="Save and exit" aria-label="Save and exit exam">×</button></div></div></header><main class="question-wrap"><div class="q-domain">${esc(q.domain)}</div>${q.select>1?`<div class="select-rule">SELECT ${q.select===2?'TWO':'THREE'} <b>${ans.length} of ${q.select} selected</b></div>`:''}<h1 class="stem">${esc(q.stem)}</h1><div class="options" role="group" aria-label="Answer options">${q.options.map((o,i)=>`<button class="option ${ans.includes(i)?'selected':''}" data-action="choose" data-index="${i}" aria-pressed="${ans.includes(i)}"><span class="choice-key">${String.fromCharCode(65+i)}</span><span class="choice-text">${esc(o)}</span></button>`).join('')}</div></main><footer class="exam-footer"><div class="exam-footer-inner"><button class="btn ghost" data-action="prev" ${a.current===0?'disabled':''}>Previous</button><div class="answered-chip">${answerCount(a)} answered</div>${a.current===c.count-1?'<button class="btn primary" data-action="submit-open">Submit exam</button>':'<button class="btn primary" data-action="next">Next</button>'}</div></footer></div>`}
function navigatorSheet(a){const c=CERTS[a.cert];return `<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="Question navigator"><div class="sheet-grab"></div><div class="sheet-head"><h2>Questions</h2><button class="icon-btn" data-action="sheet-close" aria-label="Close">×</button></div><div class="navigator">${a.questionIds.map((qid,i)=>`<button class="qnum ${a.answers[qid]?.length?'answered':''} ${a.current===i?'current':''} ${a.flags.includes(qid)?'flagged':''}" data-action="jump" data-index="${i}" aria-label="Question ${i+1}">${i+1}</button>`).join('')}</div><div class="submit-summary"><strong>${answerCount(a)} of ${c.count}</strong> answered · <strong>${a.flags.length}</strong> flagged. Unanswered questions will be scored incorrect.</div><button class="btn primary" data-action="submit-open">Submit exam</button></section></div>`}
function submitSheet(a){const c=CERTS[a.cert],un=c.count-answerCount(a);return `<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="Submit exam"><div class="sheet-grab"></div><div class="sheet-head"><h2>Submit exam?</h2><button class="icon-btn" data-action="sheet-close" aria-label="Close">×</button></div><div class="submit-summary"><strong>${answerCount(a)} of ${c.count}</strong> answered.<br>${un?`<strong>${un}</strong> unanswered question${un===1?'':'s'} will be marked incorrect.<br>`:''}<strong>${a.flags.length}</strong> question${a.flags.length===1?'':'s'} flagged for review.</div><div class="card-actions"><button class="btn ghost" data-action="sheet-close">Keep working</button><button class="btn primary" data-action="submit">Submit now</button></div></section></div>`}
function selectedText(q,sel){if(!sel?.length)return 'No answer';return sel.map(i=>`${String.fromCharCode(65+i)}. ${q.options[i]}`).join(' · ')}
function resultPage(r){stopTick();const c=CERTS[r.cert],filter=(location.hash.split('/')[2]||'all'),items=r.questionIds.map((qid,i)=>{const q=bankMaps[r.cert].get(qid),ans=r.answers[qid]||[],ok=sameSet(ans,q.correct),flag=r.flags.includes(qid);if(filter==='missed'&&ok)return '';if(filter==='flagged'&&!flag)return '';return `<article class="review-card ${ok?'good':'bad'}"><div class="status-line"><span class="status ${ok?'good':'bad'}">${ok?'Correct':'Needs review'}</span>${flag?'<span class="status flag">Flagged</span>':''}<span class="meta">Question ${i+1} · ${esc(q.domain)}</span></div><h3>${esc(q.stem)}</h3><div class="review-answer ${ok?'correct':'yours-wrong'}"><strong>Your answer:</strong> ${esc(selectedText(q,ans))}</div>${!ok?`<div class="review-answer correct"><strong>Correct answer:</strong> ${esc(selectedText(q,q.correct))}</div>`:''}<div class="rationale"><strong>Why:</strong> ${esc(q.why)}</div></article>`}).join('');return `<div class="shell">${header()}<main class="main"><div class="result-head"><div class="eyebrow">${esc(c.short)} · completed ${dateFmt(r.completedAt)}</div><h1>Exam result</h1><div class="result-big">${r.percent}%</div><div class="result-label">${r.correctCount} of ${c.count} correct · ${r.needsReview} need review</div><div class="card-actions"><button class="btn primary" data-action="retake" data-cert="${r.cert}">Take another exam</button><button class="btn ghost" data-action="go" data-route="history">History</button></div></div><div class="filter-row"><button class="pill ${filter==='all'?'active':''}" data-action="result-filter" data-id="${r.id}" data-filter="all">All questions</button><button class="pill ${filter==='missed'?'active':''}" data-action="result-filter" data-id="${r.id}" data-filter="missed">Needs review (${r.needsReview})</button><button class="pill ${filter==='flagged'?'active':''}" data-action="result-filter" data-id="${r.id}" data-filter="flagged">Flagged (${r.flags.length})</button></div><section class="review-list">${items||'<div class="empty"><strong>Nothing here.</strong>Try another review filter.</div>'}</section></main></div>`}
function render(){stopTick();openSheet=null;const h=location.hash.replace(/^#/,'')||'home';const parts=h.split('/');if(parts[0]==='exam'){const f=findAttempt(parts[1]);if(f?.type==='active')app.innerHTML=examPage(f.a);else location.hash='home';return}if(parts[0]==='result'){const r=state.history.find(x=>x.id===parts[1]);if(r)app.innerHTML=resultPage(r);else location.hash='history';return}app.innerHTML=parts[0]==='history'?historyPage():home()}
function showSheet(html){if(openSheet)openSheet.remove();const w=document.createElement('div');w.innerHTML=html;openSheet=w.firstElementChild;document.body.appendChild(openSheet);setTimeout(()=>openSheet.querySelector('button')?.focus(),0)}
function closeSheet(){openSheet?.remove();openSheet=null}
function startNew(cert){const old=state.active[cert];if(old&&!confirm('Start a fresh exam? Your current in-progress attempt for this certification will be replaced.'))return;const a=makeAttempt(cert);state.active[cert]=a;save();location.hash=`exam/${a.id}`}
function submitExam(a,auto=false){let correct=0;for(const qid of a.questionIds){const q=bankMaps[a.cert].get(qid);if(sameSet(a.answers[qid]||[],q.correct))correct++}const total=CERTS[a.cert].count,percent=Math.round(correct/total*100);const r={...a,completedAt:new Date().toISOString(),correctCount:correct,percent,needsReview:total-correct};delete state.active[a.cert];state.history=[r,...state.history.filter(x=>x.id!==r.id)].slice(0,60);save();closeSheet();location.hash=`result/${r.id}/missed`;if(auto)toast('Time ended — exam submitted')}
function currentActiveFromHash(){const p=location.hash.replace(/^#/,'').split('/');if(p[0]!=='exam')return null;const f=findAttempt(p[1]);return f?.type==='active'?f.a:null}
function move(a,delta){a.current=Math.max(0,Math.min(a.questionIds.length-1,a.current+delta));a.updatedAt=new Date().toISOString();save();render()}
function choose(a,i){const q=qFor(a),cur=(a.answers[q.id]||[]).slice();if(q.select===1){a.answers[q.id]=[i]}else if(cur.includes(i)){a.answers[q.id]=cur.filter(x=>x!==i)}else if(cur.length<q.select){a.answers[q.id]=[...cur,i]}else{toast(`Select ${q.select} answers`);return}a.updatedAt=new Date().toISOString();save();render()}
function handleAction(el){const act=el.dataset.action;if(!act)return;const a=currentActiveFromHash();switch(act){case'go':location.hash=el.dataset.route;break;case'theme':toggleTheme();break;case'new':startNew(el.dataset.cert);break;case'retake':startNew(el.dataset.cert);break;case'resume':{const x=activeAttempt(el.dataset.cert);if(x)location.hash=`exam/${x.id}`;break}case'exit':if(a){save();location.hash='home'}break;case'flag':if(a){const q=qFor(a);a.flags=a.flags.includes(q.id)?a.flags.filter(x=>x!==q.id):[...a.flags,q.id];save();render();toast(a.flags.includes(q.id)?'Flagged':'Flag removed')}break;case'navigator':if(a)showSheet(navigatorSheet(a));break;case'sheet-close':closeSheet();break;case'jump':if(a){a.current=Number(el.dataset.index);save();closeSheet();render()}break;case'choose':if(a)choose(a,Number(el.dataset.index));break;case'prev':if(a)move(a,-1);break;case'next':if(a)move(a,1);break;case'submit-open':if(a){closeSheet();showSheet(submitSheet(a))}break;case'submit':if(a)submitExam(a);break;case'review':location.hash=`result/${el.dataset.id}/all`;break;case'result-filter':location.hash=`result/${el.dataset.id}/${el.dataset.filter}`;break;case'clear-history':if(confirm('Clear all saved completed exam history? In-progress exams will be kept.')){state.history=[];save();render()}break}}
document.addEventListener('click',e=>{if(e.target.classList?.contains('sheet-backdrop')){closeSheet();return}const el=e.target.closest('[data-action]');if(el)handleAction(el)});
window.addEventListener('hashchange',render);window.addEventListener('beforeunload',()=>save());
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;const a=currentActiveFromHash();if(!a)return;const q=qFor(a);if(/^[1-5]$/.test(e.key)){const i=Number(e.key)-1;if(i<q.options.length){e.preventDefault();choose(a,i)}}else if(/^[a-eA-E]$/.test(e.key)){const i=e.key.toUpperCase().charCodeAt(0)-65;if(i<q.options.length){e.preventDefault();choose(a,i)}}else if(e.key==='ArrowRight'){e.preventDefault();move(a,1)}else if(e.key==='ArrowLeft'){e.preventDefault();move(a,-1)}else if(e.key.toLowerCase()==='f'){e.preventDefault();const qq=qFor(a);a.flags=a.flags.includes(qq.id)?a.flags.filter(x=>x!==qq.id):[...a.flags,qq.id];save();render()}});
applyTheme();render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
