(()=>{
const S=[
 {org:'a regional insurer',team:'claims operations team',data:'policy and claim documents',stake:'claim decisions',constraint:'must preserve auditability and minimize customer harm'},
 {org:'a B2B SaaS company',team:'support engineering team',data:'tickets, runbooks, and product docs',stake:'customer resolutions',constraint:'has a strict latency budget during business hours'},
 {org:'a healthcare network',team:'clinical operations team',data:'approved internal guidance and de-identified case notes',stake:'staff recommendations',constraint:'requires human review for high-impact actions'},
 {org:'a global retailer',team:'commerce platform team',data:'catalog, order, and inventory data',stake:'order operations',constraint:'must control cost across high request volume'},
 {org:'a financial services firm',team:'risk automation team',data:'policies, controls, and case evidence',stake:'risk assessments',constraint:'must satisfy least-privilege and evidence requirements'},
 {org:'a software consultancy',team:'delivery engineering team',data:'client repositories and architecture notes',stake:'production changes',constraint:'works across multiple client environments with different security boundaries'},
 {org:'a university',team:'research administration team',data:'grant rules, proposals, and internal procedures',stake:'proposal decisions',constraint:'needs consistent outputs from staff with mixed technical skill'},
 {org:'a logistics company',team:'operations platform team',data:'shipment events, SOPs, and carrier APIs',stake:'exception handling',constraint:'must remain reliable when external systems partially fail'}
];
const CERTS={
 associate:{name:'Claude Certified Associate — Foundations',short:'Associate Foundations',code:'CCAO-F',count:60,minutes:120,accent:'#cfa46d',domains:[
  ['Prompting and Task Execution',14],['Output Evaluation and Validation',21],['Product and Model Selection',12],['Workflow Integration and Solution Design',16],['Configuration and Knowledge Management',12],['Governance, Risk, and Responsible Use',15],['Troubleshooting and Optimization',10]
 ]},
 architectF:{name:'Claude Certified Architect — Foundations',short:'Architect Foundations',code:'CCAR-F',count:60,minutes:120,accent:'#79a9a1',domains:[
  ['Agentic Architecture & Orchestration',27],['Tool Design & MCP Integration',18],['Claude Code Configuration & Workflows',20],['Prompt Engineering & Structured Output',20],['Context Management & Reliability',15]
 ]},
 developerF:{name:'Claude Certified Developer — Foundations',short:'Developer Foundations',code:'CCDV-F',count:53,minutes:120,accent:'#8e9bc7',domains:[
  ['Agents & Workflows',14.7],['Applications & Integration',33.1],['Model Selection & Optimization',16.8],['Prompt & Context Engineering',11],['Tools & MCPs',10.6],['Security & Safety',8.1],['Claude Code',3.1],['Eval, Testing & Debugging',2.6]
 ]},
 architectP:{name:'Claude Certified Architect — Professional',short:'Architect Professional',code:'CCAR-P',count:63,minutes:120,accent:'#b48ac8',domains:[
  ['Solution Design & Architecture',17],['Claude Models, Prompting & Context Engineering',13],['Integration',19],['Evaluation, Testing & Optimization',16],['Governance, Safety & Risk Management',14],['Stakeholder Communication & Lifecycle Management',14],['Developer Productivity & Operational Enablement',7]
 ]}
};
const T=(d,stem,options,correct,why,select=1)=>({d,stem,options,correct:Array.isArray(correct)?correct:[correct],why,select});
const A='Prompting and Task Execution',B='Output Evaluation and Validation',C='Product and Model Selection',D='Workflow Integration and Solution Design',E='Configuration and Knowledge Management',F='Governance, Risk, and Responsible Use',G='Troubleshooting and Optimization';
const AF1='Agentic Architecture & Orchestration',AF2='Tool Design & MCP Integration',AF3='Claude Code Configuration & Workflows',AF4='Prompt Engineering & Structured Output',AF5='Context Management & Reliability';
const DV1='Agents & Workflows',DV2='Applications & Integration',DV3='Model Selection & Optimization',DV4='Prompt & Context Engineering',DV5='Tools & MCPs',DV6='Security & Safety',DV7='Claude Code',DV8='Eval, Testing & Debugging';
const P1='Solution Design & Architecture',P2='Claude Models, Prompting & Context Engineering',P3='Integration',P4='Evaluation, Testing & Optimization',P5='Governance, Safety & Risk Management',P6='Stakeholder Communication & Lifecycle Management',P7='Developer Productivity & Operational Enablement';

const associate=[
 T(A,'{org} asks Claude to draft a decision memo, but the first result is generic and misses the audience’s concerns. What is the BEST next prompt change?',['Add the decision audience, objective, constraints, relevant evidence, and explicit success criteria','Ask Claude to make the memo longer without changing the instructions','Switch models before clarifying the task','Repeat the same prompt several times and choose the longest answer'],0,'Strong prompts define the job to be done, the audience, constraints, source context, and what a successful output looks like. Length or model changes do not fix missing task definition.'),
 T(A,'The {team} has a complex request involving research, comparison, recommendation, and final drafting. What is the BEST way to improve reliability?',['Ask for all steps in one short sentence so Claude has maximum freedom','Decompose the work into explicit stages and validate important intermediate outputs','Run four unrelated chats and combine whatever sounds best','Tell Claude to never ask questions'],1,'Decomposition reduces ambiguity and gives the user checkpoints to catch errors before they propagate into the final deliverable.'),
 T(A,'A first Claude draft for {stake} is close, but one section uses the wrong tone and omits two required constraints. What is the BEST next action?',['Start from scratch with a completely different task','Provide targeted feedback naming the tone issue and missing constraints, then iterate','Accept it because repeated prompting always degrades quality','Only change the temperature setting'],1,'Iterative prompting with specific feedback is usually more efficient than restarting when the structure is already useful.'),
 T(B,'Claude produces a polished summary from {data}, including three numerical claims that will be sent to executives. What should the user do FIRST before relying on it?',['Assume polished language indicates factual accuracy','Verify the important claims against the authoritative source material','Ask Claude whether it is confident and accept a high-confidence answer','Remove the numbers so verification is unnecessary'],1,'Fluency is not evidence. Material factual claims should be checked against authoritative sources, especially before consequential use.'),
 T(B,'A response from Claude appears complete but cites a policy clause that the user cannot find in the approved source set. What is the BEST interpretation?',['The policy probably changed, so the response should be trusted','Treat the clause as unverified and check the source before using it','The citation format proves the clause exists','Ask Claude to generate a more convincing citation'],1,'A missing or unverifiable source is a validation failure, not a formatting issue. The claim must be checked before use.'),
 T(B,'The {team} wants to judge whether a generated customer-facing explanation is ready. Which TWO checks are most important?',['Whether the wording is confident','Whether the claims are supported by the provided facts','Whether the answer satisfies the requested audience and format','Whether it uses the maximum available context'],[1,2],'Evaluation should focus on factual support and fitness for the intended audience/task, not confidence or token usage.',2),
 T(C,'{org} must process a very high volume of simple classification tasks where latency and cost matter more than deep reasoning. Which model-selection principle is BEST?',['Always use the most capable model regardless of task','Start with a smaller/faster model and validate that quality meets the requirement','Use a larger model because smaller models cannot follow instructions','Choose based only on the newest release date'],1,'Model selection should match capability to the task and quality threshold while accounting for latency and cost.'),
 T(C,'A user needs sustained work over a set of recurring internal documents and instructions. Which Claude setup is generally MOST appropriate?',['A fresh chat with no context every time','A Project with curated knowledge and durable project instructions','An image-generation workflow','A larger model with no supporting context'],1,'Projects are designed to keep recurring work grounded in shared instructions and knowledge without repeatedly reconstructing context.'),
 T(C,'A task involves difficult synthesis across ambiguous evidence and the cost of an error is high. What is the BEST model-selection approach?',['Prefer the cheapest model without testing','Use a more capable model, then validate outputs against acceptance criteria','Use any model because prompts eliminate capability differences','Avoid supplying evidence so the model can reason freely'],1,'Higher-complexity, higher-stakes work justifies more capability, but output validation remains necessary.'),
 T(D,'The {team} wants Claude to help with {stake}. Some actions are reversible drafts; others directly change a production system. What is the BEST workflow design?',['Let Claude perform every action automatically for consistency','Use automation for low-risk reversible steps and require review before high-impact irreversible actions','Require manual approval after every sentence','Remove Claude from all workflow stages'],1,'Good workflow design applies human review according to risk and reversibility rather than treating all steps the same.'),
 T(D,'A recurring process currently requires staff to copy information between several systems, summarize it, and prepare a draft recommendation. What is the BEST first automation target?',['Automate the entire end-to-end process before measuring it','Start with a bounded, repeatable step with clear inputs, outputs, and review criteria','Automate only the most ambiguous judgement step','Replace the existing systems before using Claude'],1,'A bounded step with clear interfaces and evaluation criteria reduces implementation risk and makes value measurable.'),
 T(D,'{org} is redesigning a workflow with Claude. Which TWO questions most directly determine where Claude should be used?',['Which steps are repetitive or language-heavy and have clear success criteria?','Which steps are high-impact and require accountable human judgement?','Which steps have the longest names in the process map?','Which team member uses the newest laptop?'],[0,1],'Good solution design identifies where AI adds leverage and where risk or accountability requires a human decision.',2),
 T(E,'The same team repeatedly asks Claude to follow the same terminology, style, and internal rules. Where should stable instructions live?',['Only in each user’s memory','In durable project/workspace instructions that are maintained with the workflow','In random examples pasted into some chats','In the browser history'],1,'Stable, reusable guidance belongs in maintained instructions rather than relying on users to reconstruct it each time.'),
 T(E,'A Project contains ten old files and two current policy files. Claude sometimes answers from obsolete guidance. What is the BEST fix?',['Add more unrelated files to provide context','Curate the knowledge set so current authoritative sources are clear and obsolete material is removed or labeled','Tell Claude that all files are equally correct','Use a longer prompt but keep the conflicting files'],1,'Knowledge quality matters more than volume. Conflicting or stale sources should be curated so the model receives reliable context.'),
 T(E,'A team shares a Claude workflow across many users. Which configuration practice BEST improves consistency?',['Document reusable instructions and keep shared knowledge sources governed and current','Let each user invent their own hidden rules','Change model and prompt at the same time whenever output changes','Avoid naming the expected output format'],0,'Consistency comes from governed shared instructions and knowledge, with changes made deliberately rather than implicitly.'),
 T(F,'A user is preparing to upload customer records to Claude for a drafting task. The workflow does not require all fields. What is the BEST practice?',['Upload the full dataset because more context is always better','Minimize the data to what is needed and follow organizational access and privacy rules','Paste credentials into the prompt so Claude can fetch more data','Use personal accounts to avoid company restrictions'],1,'Responsible use includes data minimization, approved access, and adherence to privacy and organizational policy.'),
 T(F,'Claude recommends an action that could materially affect a person’s eligibility for a service. What is the BEST operating principle?',['Treat Claude as the final accountable decision maker','Use appropriate human review, clear policy criteria, and documented evidence before the action is finalized','Hide the use of Claude so users are not confused','Accept the recommendation if it is written confidently'],1,'High-impact decisions require accountable review and evidence. Claude can assist, but governance cannot be delegated to model confidence.'),
 T(F,'Which TWO controls most directly reduce responsible-use risk in a recurring workflow?',['Define what data Claude may receive and who can access the workflow','Define when human review or escalation is required','Use the largest model for every request','Keep all prompts undocumented so users can adapt freely'],[0,1],'Data boundaries and explicit review/escalation rules are core governance controls.',2),
 T(G,'A previously reliable workflow begins producing inconsistent answers after its knowledge files were updated. What should the team do FIRST?',['Change every prompt and model setting at once','Compare the changed knowledge/instructions and reproduce failures with representative examples','Assume Claude is temporarily broken','Increase response length'],1,'Troubleshooting should isolate recent changes and reproduce the failure before making multiple simultaneous changes.'),
 T(G,'A long prompt contains repeated instructions, outdated notes, and multiple conflicting examples. Output quality has become unstable. What is the BEST optimization?',['Add more examples without removing anything','Remove redundant or conflicting context and keep the most relevant authoritative instructions','Repeat every rule twice','Increase verbosity in the answer'],1,'Cleaner context reduces conflicts and makes important instructions easier for the model to follow.'),
 T(G,'The {team} says Claude is “sometimes wrong.” What is the BEST next diagnostic step?',['Ask users for concrete failed examples and classify the failure pattern','Replace the entire workflow immediately','Measure only user satisfaction without looking at outputs','Turn off review so more data is generated'],0,'Concrete examples let the team distinguish prompt, source, workflow, or validation problems and choose the right fix.')
];

const architectF=[
 T(AF1,'{org} has a process with fixed validation steps and a small number of known branches. The team is considering a fully autonomous agent. What is the BEST architecture?',['Use an agent because agents are always more capable','Prefer a deterministic workflow for known steps and reserve agentic behavior for genuinely open-ended decisions','Use multiple agents so every step has a separate model','Remove validation because the workflow is deterministic'],1,'When the path is known, deterministic orchestration is easier to reason about, test, and control. Agentic loops are justified by uncertainty, not novelty.'),
 T(AF1,'An agent for {stake} can call tools repeatedly and has no explicit termination rule. What is the MOST important reliability improvement?',['Increase the model context window','Define success/stop conditions plus step, time, or cost budgets','Give the agent more tools','Remove tool error messages'],1,'Agentic loops need explicit termination and resource budgets to prevent runaway execution and make failure predictable.'),
 T(AF1,'A coordinator delegates independent research tasks to subagents. What context should each subagent receive?',['The entire parent transcript by default','Only the task-specific context and constraints required to complete its assignment','No context, because subagents should infer the goal','Every other subagent’s private scratch work'],1,'Scoped context reduces noise, token cost, and accidental coupling while preserving the information needed for the delegated task.'),
 T(AF1,'A workflow can automatically prepare a refund recommendation, but issuing the refund is irreversible above a threshold. What is the BEST orchestration pattern?',['Let the agent issue every refund to reduce latency','Place a human approval gate before the irreversible high-impact action','Ask a second agent to approve every refund','Disable automation for the entire workflow'],1,'Human approval belongs at high-impact irreversible boundaries; lower-risk preparation can remain automated.'),
 T(AF2,'The team is designing a tool that updates an order. Which tool schema is BEST?',['A single free-form string describing any possible action','A narrowly scoped schema with explicit required fields, types, constraints, and clear error responses','A schema containing every field from the underlying database','No description because the model can infer the API'],1,'Tools should expose a small, clear contract that makes valid calls easy and invalid calls explicit.'),
 T(AF2,'An MCP server exposes a large policy document that Claude may read, but reading it should not perform an action. Which MCP primitive is the BEST fit?',['Tool','Resource','Prompt','Hook'],1,'Resources expose readable context/data; tools perform actions; prompts provide reusable prompt templates.'),
 T(AF2,'{org} connects Claude to an internal ticketing system through MCP. Which security design is BEST?',['Give the MCP server a global administrator credential','Use least-privilege credentials and authorize actions at the integration boundary','Put the credential in the system prompt','Rely on the model to refuse unauthorized requests without backend checks'],1,'Authorization must be enforced outside the model with least-privilege credentials and server-side policy.'),
 T(AF2,'Which TWO tool-design choices improve reliability for an agent?',['Return structured, actionable errors that distinguish retryable from non-retryable failures','Keep tool descriptions and parameter semantics unambiguous','Expose many overlapping tools with similar names','Silently coerce invalid inputs into arbitrary defaults'],[0,1],'Clear contracts and structured errors help the model select tools and recover correctly.',2),
 T(AF3,'A repository needs durable guidance about architecture, commands, conventions, and how Claude should work in the codebase. What is the BEST place?',['CLAUDE.md and scoped instruction files maintained with the repository','A developer’s private chat history','Comments pasted into every prompt manually','The package lockfile'],0,'CLAUDE.md and scoped instructions provide durable project context that travels with the codebase.'),
 T(AF3,'The team wants a command to run automatically before a risky Claude Code action so policy can inspect or block it. What mechanism BEST fits?',['A hook','A larger model','A markdown heading','A Project knowledge file'],0,'Hooks intercept lifecycle events and can enforce or automate behavior around Claude Code actions.'),
 T(AF3,'A shared Claude Code setup should allow read-only exploration broadly but require explicit approval before destructive shell commands. What is the BEST approach?',['Disable all permissions','Configure permissions by risk level rather than granting blanket access','Put “be careful” in a comment and allow everything','Store administrator credentials in CLAUDE.md'],1,'Permission models should align capability with task risk, avoiding both blanket denial and blanket authority.'),
 T(AF3,'Which TWO items are appropriate for durable repository-level Claude Code configuration?',['Project conventions and build/test commands','Secrets and production tokens','Scoped rules for specific paths or task types','Personal unrelated preferences for one developer'],[0,2],'Repository guidance should capture shared project knowledge and scoped rules; secrets should never be stored there.',2),
 T(AF4,'Claude must return data that a downstream system parses automatically. What is the BEST prompt/output strategy?',['Ask for a persuasive paragraph and parse it heuristically','Specify a strict structured schema and validate the returned fields before use','Ask Claude to choose any format it prefers','Use markdown tables because they are always machine-safe'],1,'Machine-consumed output should use explicit structure plus validation instead of relying on prose formatting.'),
 T(AF4,'A complex extraction prompt mixes source text, instructions, and examples, and Claude occasionally treats source text as instructions. What is the BEST improvement?',['Use clear delimiters or XML-style sections that separate instructions, examples, and untrusted content','Remove all examples','Repeat the source text twice','Ask Claude to ignore every future instruction'],0,'Explicit structure clarifies the role of each block and reduces ambiguity between instructions and data.'),
 T(AF4,'A task has subtle formatting and classification requirements that are difficult to express only as prose. What technique is MOST helpful?',['Provide a few representative examples that demonstrate the desired mapping','Increase output length','Remove the success criteria','Use a random system prompt each run'],0,'Few-shot examples can make nuanced output patterns concrete when they represent the target behavior well.'),
 T(AF4,'Which TWO prompt elements most directly improve a structured production task?',['Explicit success criteria and constraints','A clearly defined output schema','Unrelated background to fill the context window','Instructions that intentionally conflict so Claude reasons harder'],[0,1],'Clear criteria and a defined schema reduce ambiguity and make outputs testable.',2),
 T(AF5,'A long-running agent repeatedly carries the entire conversation, tool logs, and old intermediate text forward until performance degrades. What is the BEST strategy?',['Keep everything forever because more context is always better','Maintain a compact task state, preserve necessary facts, and drop or summarize obsolete detail','Restart after every tool call','Hide tool results from the agent'],1,'Context is a budget. Reliable systems preserve decision-relevant state while removing stale or redundant detail.'),
 T(AF5,'A retrieval workflow returns many semantically similar but irrelevant chunks, causing answers to drift. What should the architect improve FIRST?',['The retrieval and chunking strategy against representative queries','The color of the user interface','The response font size','The number of agents'],0,'Poor grounding is primarily a retrieval-quality problem; evaluate chunking, indexing, query formulation, and ranking against real queries.'),
 T(AF5,'An external tool sometimes times out. The agent currently treats an empty result as success and continues. What is the BEST fix?',['Return explicit error states and define retry/escalation behavior','Increase model temperature','Remove the timeout','Tell the user failures are impossible'],0,'Failures must be represented explicitly so the orchestration can retry, fall back, or escalate instead of hallucinating success.'),
 T(AF5,'Which TWO practices best support reliable long tasks?',['Checkpoint validated intermediate state','Carry only context needed for the next decisions','Keep every raw token from every earlier step','Retry forever until a tool succeeds'],[0,1],'Checkpointing and context curation keep long-running work recoverable and focused.',2)
];

const developerF=[
 T(DV1,'A workflow has a known three-step sequence and every branch is defined in code. The team proposes replacing it with an autonomous agent loop. What is the BEST choice?',['Keep the deterministic workflow unless open-ended reasoning is actually required','Always use an agent because it is more modern','Use two agents to vote on every branch','Remove the branch logic and put it all in one prompt'],0,'Agents are useful when the next action cannot be fully predetermined. Fixed business logic is usually clearer and safer in code.'),
 T(DV1,'An agent can execute changes in an external system. Which design BEST limits runaway behavior?',['Unbounded retries and unlimited tool calls','Explicit stop conditions, budgets, and approval gates for high-impact actions','A longer system prompt only','A second agent with the same permissions'],1,'Production agents need bounded loops and control points around costly or irreversible actions.'),
 T(DV1,'A coordinator uses subagents for independent tasks. Which TWO design choices are strongest?',['Give each subagent a narrow objective and only relevant context','Aggregate validated outputs in the coordinator','Share all secrets with every subagent','Let subagents recursively spawn without limits'],[0,1],'Narrow delegation and controlled aggregation reduce context pollution and uncontrolled execution.',2),
 T(DV2,'Claude requests a tool call through the Messages API. What must the application do next?',['Execute the requested tool under application policy, then return the tool result in the next model turn','Assume the tool already ran on Anthropic servers','Convert the tool request into a system prompt','Ignore the request and resend the same user message'],0,'With client-executed tools, the application owns execution, authorization, error handling, and returning results to the model.'),
 T(DV2,'A client streams a long response to the UI. Which implementation is MOST robust?',['Append raw network chunks directly and assume each chunk is a complete message','Handle typed stream events, partial content, errors, and finalization explicitly','Disable cancellation so the stream cannot be interrupted','Buffer forever before showing any output'],1,'Streaming integrations should process protocol events and failure/final states rather than assuming arbitrary network chunks are semantic units.'),
 T(DV2,'{org} has 80,000 non-urgent independent classification requests that can complete later. Which API pattern is the BEST fit?',['Send every request synchronously from the user interface','Use batch processing designed for asynchronous bulk work','Create one enormous prompt containing every record','Run an agent that loops through all records interactively'],1,'Batch APIs are designed for large, independent, non-latency-sensitive workloads and can improve throughput/cost characteristics.'),
 T(DV2,'A production service must parse Claude output into a typed object. What is the BEST engineering practice?',['Parse arbitrary prose with regular expressions','Request constrained structured output and validate it before downstream use','Trust valid-looking JSON without schema checks','Write the expected JSON in a comment after the call'],1,'Structured output plus application validation creates a reliable boundary between model output and code.'),
 T(DV2,'An API integration occasionally retries a request after a transient network failure. Which concern is MOST important for actions with side effects?',['Make retries idempotent or otherwise prevent duplicate side effects','Increase response creativity','Remove request IDs','Retry all failures forever'],0,'Retry behavior must account for duplicate execution when the operation changes state.'),
 T(DV2,'The application supports image input alongside text. What should determine whether image content is included?',['Whether the model supports the modality and the task actually requires the visual information','Whether images make prompts look more advanced','Always attach screenshots of the full desktop','Never combine modalities'],0,'Inputs should match supported capabilities and task requirements; extra data adds cost and potential privacy risk.'),
 T(DV3,'A high-volume extraction endpoint is simple and well evaluated. Which model strategy BEST controls cost without sacrificing requirements?',['Benchmark a smaller/faster model and use it if it meets the quality target','Always route to the largest model','Select a model only by price with no evaluation','Randomize the model each request'],0,'Model routing should be evidence-based: use the least expensive/fastest model that meets the measured quality requirement.'),
 T(DV3,'A repeated system prompt and reference block are large and stable across many requests. Which optimization should be evaluated?',['Prompt caching for reusable prefix content','Adding random text to make each request unique','Re-sending the prefix in multiple user messages','Disabling token accounting'],0,'Prompt caching is useful when a substantial prefix is reused and the workload satisfies caching requirements.'),
 T(DV3,'A complex reasoning path fails quality checks on a smaller model but passes on a more capable one. What is the BEST production design?',['Route all traffic to the larger model forever','Use task-aware routing or escalation so difficult cases receive the more capable model','Ignore the quality checks','Increase temperature on the smaller model until it becomes equivalent'],1,'Selective escalation can preserve quality while avoiding unnecessary cost on simpler requests.'),
 T(DV4,'A prompt includes instructions, retrieved documents, and a user request. How should the developer reduce ambiguity?',['Separate the sections clearly and state how retrieved/untrusted text should be treated','Concatenate everything without labels','Put the user request in the system prompt','Repeat all retrieved text twice'],0,'Explicit context structure helps preserve instruction hierarchy and reduces accidental instruction-following from retrieved content.'),
 T(DV4,'A recurring task has nuanced target behavior and zero-shot instructions are inconsistent. What is the BEST next technique?',['Add representative few-shot examples and evaluate again','Increase randomness','Remove constraints','Use larger outputs as a proxy for correctness'],0,'Representative examples can teach subtle mappings, but their effect should be measured with evals.'),
 T(DV4,'Which TWO context practices are strongest for long-running application workflows?',['Carry forward only decision-relevant state','Summarize/checkpoint validated progress','Keep every log line indefinitely in the model context','Insert credentials so the model can recover missing data'],[0,1],'Context should be curated and checkpointed rather than allowed to grow without bound.',2),
 T(DV5,'An MCP tool changes customer records. Where should authorization be enforced?',['Only in the natural-language tool description','In the server/application boundary using authenticated identity and least-privilege policy','By asking Claude whether the user seems trustworthy','Inside a hidden example in the prompt'],1,'Tool descriptions guide the model but cannot replace server-side authentication and authorization.'),
 T(DV5,'A tool accepts a free-form object with dozens of optional fields and Claude often calls it incorrectly. What is the BEST fix?',['Narrow and clarify the schema, required fields, enums, descriptions, and error responses','Increase the model temperature','Rename every field to one letter','Return success for malformed inputs'],0,'Good tool schemas make the valid action space explicit and easy for the model to navigate.'),
 T(DV5,'Which TWO MCP design decisions improve maintainability?',['Expose focused capabilities instead of one giant “do anything” tool','Keep protocol-level data/resources separate from state-changing tools','Embed administrator credentials in configuration examples','Create multiple overlapping tools with unclear boundaries'],[0,1],'Focused capabilities and clean primitive boundaries improve security, discoverability, and testing.',2),
 T(DV6,'Retrieved web content contains instructions telling Claude to ignore policy and invoke a privileged tool. What is the BEST defense?',['Treat retrieved content as untrusted data and enforce tool authorization outside the model','Tell Claude once that prompt injection never works','Allow the call if the content looks professional','Put the privileged credential in the context so Claude can verify it'],0,'Prompt injection is an untrusted-input problem. Authorization and data boundaries must not depend on model obedience.'),
 T(DV6,'Where should API keys and production secrets be stored?',['In source-controlled prompts','In an approved secret-management mechanism outside model context and source code','In CLAUDE.md for team convenience','In tool descriptions'],1,'Secrets should be handled by secret-management and runtime configuration, not prompts or source-controlled instructions.'),
 T(DV6,'A tool can delete data. Which TWO controls are strongest?',['Require explicit authorization for the operation','Use confirmation or human approval where the action is high impact','Rely on a polite system prompt as the only safeguard','Automatically retry deletion on every error'],[0,1],'Sensitive state changes require policy enforcement and, where appropriate, confirmation or human review.',2),
 T(DV7,'A team wants Claude Code to understand repo-specific commands, conventions, and architecture. What should be maintained?',['CLAUDE.md / scoped project instructions','A shared spreadsheet outside the repo only','Production credentials in a markdown file','A different ad hoc prompt for each developer'],0,'Durable project context belongs in repository instructions that can be reviewed and versioned.'),
 T(DV7,'Claude Code should explore broadly but ask before destructive commands. What should the team configure?',['A permission policy matching command risk','No permissions at all','Administrator access by default','Only response verbosity'],0,'Permissions should grant the minimum authority needed while preserving useful low-risk operations.'),
 T(DV8,'A prompt change improves five demo cases. What is the BEST evidence before deploying it?',['Run a representative regression eval set with defined acceptance criteria','Trust the developer’s impression','Check only the five examples used during editing','Deploy first and evaluate only if users complain'],0,'A representative eval suite guards against regressions and overfitting to the examples used during prompt development.'),
 T(DV8,'Production quality drops intermittently. Which TWO signals are most useful for debugging?',['Traces linking inputs, model/tool events, outputs, and errors','Versioned prompt/model/config metadata','Only aggregate token count with no request linkage','Developer memory of what probably happened'],[0,1],'Traceability and version metadata let engineers reproduce and isolate failures.',2)
];

const architectP=[
 T(P1,'{org} wants to automate a process whose steps are stable except for a small ambiguous triage stage. Which architecture is MOST defensible?',['Use a fully autonomous agent for the entire process','Use a deterministic workflow and confine agentic reasoning to the ambiguous stage','Use multiple agents for every deterministic step','Move all business rules into a single system prompt'],1,'Professional architecture should minimize unnecessary autonomy: deterministic controls for known logic, agentic reasoning where uncertainty genuinely requires it.'),
 T(P1,'During discovery, stakeholders describe a broad goal to “use Claude to improve {stake}.” What should the architect produce BEFORE selecting components?',['A scoped problem statement with users, decisions, constraints, success criteria, and non-goals','A final vendor diagram','A list of every Claude feature','A fixed model choice'],0,'Architecture starts by translating business intent into a bounded problem and measurable outcomes; component choices follow.'),
 T(P1,'A solution has several independent analysis stages that can run concurrently and a final synthesis step. What pattern is BEST?',['Serial execution of every stage regardless of dependencies','Parallelize independent stages and coordinate validated outputs for synthesis','One unbounded agent loop for all work','Duplicate every stage and pick a random result'],1,'Decomposition should reflect dependency structure. Independent work can run in parallel while synthesis remains coordinated.'),
 T(P2,'A service has a hard latency SLO and mixed request complexity. What model strategy is BEST?',['Always use the largest model to maximize capability','Use measured routing: a fast model for routine cases with escalation for complex cases that need more capability','Choose a model based only on benchmark headlines','Switch models randomly to average performance'],1,'Professional model strategy balances measured quality, latency, and cost against the actual workload.'),
 T(P2,'A large policy prefix is reused across many calls and changes infrequently. What optimization should be considered?',['Prompt caching while keeping cache boundaries aligned to stable content','Adding timestamps to every line so the prefix is always unique','Duplicating the prefix in the user message','Removing usage instrumentation'],0,'Caching stable repeated context can reduce repeated processing cost/latency when implemented with appropriate boundaries.'),
 T(P2,'A team keeps adding context to fix errors, but the prompt now contains redundant rules and stale examples. What is the BEST architectural response?',['Curate and modularize context, preserving authoritative high-value instructions and removing conflict','Keep adding context because more is always safer','Move all context into one unlabeled user message','Use a larger context window as the only fix'],0,'Context engineering is about relevance and structure, not maximum volume.'),
 T(P3,'A RAG system retrieves long policy documents but answers often miss exact clauses buried within them. What should the architect evaluate FIRST?',['Chunking boundaries, metadata, retrieval strategy, and ranking against representative queries','The front-end theme','The number of dashboard charts','Whether a second LLM should rewrite all documents'],0,'Retrieval quality depends on how data is segmented, indexed, queried, and ranked. Those should be tested before adding architectural complexity.'),
 T(P3,'An enterprise MCP integration currently uses one shared service credential for all users. What is the PRIMARY concern?',['The UI may be slower','User identity and authorization boundaries are lost, creating excessive privilege and weak auditability','The model may write shorter answers','MCP cannot use authentication'],1,'Enterprise integrations must preserve identity, authorization, and evidence. Shared broad credentials undermine least privilege and accountability.'),
 T(P3,'A client asks whether an internal capability should be exposed through MCP or called directly through an application API. What should drive the choice?',['Which mechanism best fits the clients, lifecycle, security boundary, discoverability, and interoperability requirements','Always choose MCP because it is newer','Always choose direct REST because protocols are unnecessary','Choose whichever has the shorter name'],0,'Integration mechanism is an architectural trade-off, not a branding choice. The surrounding clients and governance boundary matter.'),
 T(P3,'At scale, the team cannot explain why some agent requests become slow or expensive. Which capability is MOST important?',['End-to-end observability across model calls, retrieval, tools, retries, latency, cost, and outcomes','More detailed UI animations','A larger context window','More autonomous subagents'],0,'Production integration requires telemetry that ties system behavior to latency, cost, reliability, and outcome signals.'),
 T(P4,'A proposed architecture change improves average response quality but the team has no defined release gate. What should the architect establish?',['A versioned evaluation suite with representative cases, explicit metrics, and acceptance thresholds','A subjective demo meeting only','A policy that every newer model is automatically approved','A single golden question'],0,'Evaluation should be a repeatable acceptance gate, not an impression after implementation.'),
 T(P4,'Two prompt strategies are candidates for production. What is the BEST comparison?',['Run controlled evaluation on representative data while measuring quality, latency, and cost','Ask the author of each prompt which is better','Compare only token length','Deploy both without logging outcomes'],0,'Architecture choices should be evaluated across the operational dimensions the system is expected to meet.'),
 T(P4,'Production errors increased after a model, prompt, and retrieval index were changed in the same release. What is the FIRST problem with this rollout?',['Too many variables changed simultaneously, weakening causal diagnosis','The release should have included more UI changes','Models cannot be versioned','Retrieval changes never affect answer quality'],0,'Controlled changes and versioned telemetry are essential to isolating regressions.'),
 T(P5,'A system can recommend and execute high-impact actions. Which safety stack is MOST defensible?',['Prompt-level warnings only','Layered controls: input handling, constrained tools, authorization, output checks, and human review based on risk','A second model with identical permissions as the only guardrail','Trust the model because the system prompt says to be safe'],1,'Professional safety is defense in depth. Model instructions are one layer, not the enforcement boundary.'),
 T(P5,'A compliance requirement says access to sensitive records must be limited and auditable. What should the architecture map it to?',['Named technical controls, responsible owners, and evidence that the controls operate','A general promise in the project charter','A hidden instruction to Claude','A larger model'],0,'Governance obligations should map to concrete controls, ownership, and evidence that can survive review.'),
 T(P5,'Which TWO factors most strongly justify a human decision gate?',['The action is difficult to reverse','The cost or harm of a wrong decision is high','The response is longer than 500 tokens','The model used a tool'],[0,1],'Human review should be risk-based, especially around irreversibility and consequence severity.',2),
 T(P6,'A stakeholder asks for a guarantee that an LLM workflow will be “100% correct.” What is the BEST architect response?',['Agree to the guarantee to secure approval','Explain probabilistic behavior, define measurable service/quality targets, controls, and escalation for failures','Avoid discussing reliability','Promise correctness if the largest model is used'],1,'Stakeholder communication should set defensible expectations and translate uncertainty into measurable controls and operating procedures.'),
 T(P6,'A major architecture choice trades lower latency for higher cost. What artifact BEST supports future teams?',['An architecture decision record documenting context, options, decision, trade-offs, and consequences','A private chat message','A screenshot of the final diagram only','A meeting with no written outcome'],0,'ADRs preserve why a decision was made, enabling future operators to revisit it with context.'),
 T(P6,'Before handoff, what should the architect ensure?',['Operational ownership, runbooks, alerts, known limits, escalation paths, and change/evaluation procedures are documented and accepted','Only the source code is delivered','The architect remains the permanent single point of failure','The team receives a presentation but no access or runbook'],0,'A production design must outlast its original architect. Handoff includes ownership and the operating system around the code.'),
 T(P7,'A platform team wants dozens of developers to use Claude Code consistently across repositories. What is the BEST enablement approach?',['Provide versioned shared instructions, permissions, reusable skills/plugins, examples, and onboarding guidance','Give everyone unrestricted defaults and rely on tribal knowledge','Centralize all work through one architect’s laptop','Prevent teams from customizing anything even when repository needs differ'],0,'Enablement scales through reusable, governed defaults plus documented extension points.'),
 T(P7,'A team repeatedly encounters the same operational failure pattern. What should the architect do after the immediate incident is resolved?',['Feed the learning into runbooks, tests/evals, shared configuration, and monitoring so recurrence becomes less likely','Treat each recurrence as unrelated','Delete the logs','Add more autonomy without changing controls'],0,'Operational enablement converts incidents into reusable system improvements.'),
 T(P7,'Which TWO artifacts best reduce dependence on the original solution architect?',['Clear runbooks and escalation ownership','Versioned reusable configuration with documented rationale','Unwritten personal shortcuts','Administrator credentials shared in chat'],[0,1],'Operational knowledge and configuration should be explicit, reviewable, and transferable.',2)
];

const templates={associate,architectF,developerF,architectP};
function fill(x,s){return x.replaceAll('{org}',s.org).replaceAll('{team}',s.team).replaceAll('{data}',s.data).replaceAll('{stake}',s.stake).replaceAll('{constraint}',s.constraint)}
function buildBank(cert){const ts=templates[cert];const out=[];ts.forEach((t,ti)=>S.forEach((s,si)=>out.push({id:`${cert}-${ti}-${si}`,cert,domain:t.d,stem:fill(t.stem,s),options:t.options.map(x=>fill(x,s)),correct:t.correct.slice(),select:t.select,why:fill(t.why,s)})));return out}
window.CLAUDE_CERT={CERTS,buildBank};
})();
